
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.table.DefaultTableModel;


/**
 * Admin girişinden sonraki emanet otomasyon ekranıdır
 */
public class frmGirdi extends javax.swing.JFrame {
    private frmIntro frm1;
    private ArrayList<Musteri> kullanicilar;
    
    DefaultTableModel dtm = new DefaultTableModel (); 
    
    
    /**
     * Creates new form frmGirdi
     * @param frm2
     */
    public frmGirdi(frmIntro frm2 ) throws FileNotFoundException, IOException {
        initComponents();
        this.frm1 = frm2;
        frm1.setVisible(false); 
        
        this.kullanicilar = new ArrayList<>();
     
        jTable1.setModel(dtm);
        dtm.setColumnIdentifiers(new String [] {"İsim","Soyisim","Esya İsmi"});
        
        String dosyaadi = "VeriTabani.txt" ;        
        File file = new File(dosyaadi);    
        Scanner in = new Scanner(file);
        while(in.hasNextLine()) {
            String isim = in.nextLine();
            String soyisim = in.nextLine();
            String esya = in.nextLine();
            this.kullanicilar.add(new Musteri(isim,soyisim,esya));
            dtm.addRow(new String[] {isim,soyisim,esya} );
        } 
        in.close();
        txtHata.setText(" ");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnKaydet = new javax.swing.JButton();
        lblBaslik = new javax.swing.JLabel();
        lblAd = new javax.swing.JLabel();
        txtAd = new javax.swing.JTextField();
        lblSoyad = new javax.swing.JLabel();
        txtSoyad = new javax.swing.JTextField();
        lblEsya = new javax.swing.JLabel();
        txtEsya = new javax.swing.JTextField();
        btnEkle = new javax.swing.JButton();
        btnCikar = new javax.swing.JButton();
        txtHata = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAdmin2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EMANET YÖNETİM SİSTEMİ");
        setBackground(new java.awt.Color(0, 153, 102));
        setResizable(false);

        btnKaydet.setBackground(new java.awt.Color(204, 204, 255));
        btnKaydet.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnKaydet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kaydet.png"))); // NOI18N
        btnKaydet.setText("Dosyaya Kaydet");
        btnKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaydetActionPerformed(evt);
            }
        });

        lblBaslik.setBackground(new java.awt.Color(51, 255, 255));
        lblBaslik.setFont(new java.awt.Font("Constantia", 1, 34)); // NOI18N
        lblBaslik.setForeground(new java.awt.Color(204, 0, 51));
        lblBaslik.setText("EMANET YÖNETİM SİSTEMİ");

        lblAd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAd.setForeground(new java.awt.Color(0, 51, 255));
        lblAd.setText("Müşteri Adı :");

        txtAd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtAd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAdFocusGained(evt);
            }
        });

        lblSoyad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSoyad.setForeground(new java.awt.Color(0, 51, 255));
        lblSoyad.setText("Müşteri Soyadı :");

        txtSoyad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSoyad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSoyadFocusGained(evt);
            }
        });

        lblEsya.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEsya.setForeground(new java.awt.Color(0, 51, 255));
        lblEsya.setText("Emanet Eşyanın İsmi :");

        txtEsya.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEsya.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEsyaFocusGained(evt);
            }
        });

        btnEkle.setBackground(new java.awt.Color(204, 204, 255));
        btnEkle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEkle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teslim al.png"))); // NOI18N
        btnEkle.setText("Bilgileri Ekleyerek Teslim Al");
        btnEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEkleActionPerformed(evt);
            }
        });

        btnCikar.setBackground(new java.awt.Color(204, 204, 255));
        btnCikar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCikar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teslim et.png"))); // NOI18N
        btnCikar.setText("Tablodan Seçerek Teslim Et");
        btnCikar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCikarActionPerformed(evt);
            }
        });

        txtHata.setEditable(false);
        txtHata.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtHata.setForeground(new java.awt.Color(204, 0, 0));
        txtHata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHataActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnAdmin2.setBackground(new java.awt.Color(204, 204, 255));
        btnAdmin2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAdmin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/door-in-icon.png"))); // NOI18N
        btnAdmin2.setText("ÇIKIŞ");
        btnAdmin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmin2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtHata, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnKaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnAdmin2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(btnCikar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEsya, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSoyad, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAd, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEsya, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtAd, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtSoyad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblBaslik, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBaslik, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAd)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSoyad)
                            .addComponent(txtSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEsya, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEsya, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))))
                .addGap(18, 25, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCikar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHata, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdmin2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAdmin2, btnKaydet});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCikar, btnEkle});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCikarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCikarActionPerformed
        try {
            String ad = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
            txtAd.setText("");
            String soyad = jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
            txtSoyad.setText("");
            String esya = jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString();
            txtEsya.setText("");
            if(ad.compareTo("") != 0 && soyad.compareTo("") != 0 && esya.compareTo("") != 0 && jTable1.getSelectedRow() >= 0) {
                dtm.removeRow(jTable1.getSelectedRow() );
                int i;
                for(i=0 ; i<kullanicilar.size() ; i++ ) {
                    if(this.kullanicilar.get(i).getIsim().compareTo(ad)==0 && this.kullanicilar.get(i).getSoyisim().compareTo(soyad)==0 && this.kullanicilar.get(i).getEsyasi().compareTo(esya)==0 ) {
                        this.kullanicilar.remove(i);
                        break;
                    }
                }
                txtHata.setText("Başarıyla Silindi.");
            } else {
                txtHata.setText("Eksik bilgiyle silinemez !");
            }
        }catch (Exception exception) {
            txtHata.setText("Tablodan seçerek siliniz !!!");
        }
    }//GEN-LAST:event_btnCikarActionPerformed

    private void txtHataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHataActionPerformed

    private void btnEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEkleActionPerformed
        String ad = txtAd.getText();
        txtAd.setText("");
        String soyad = txtSoyad.getText();
        txtSoyad.setText("");
        String esya = txtEsya.getText();
        txtEsya.setText("");
        if(ad.compareTo("") != 0 && soyad.compareTo("") != 0 && esya.compareTo("") != 0) {
            dtm.addRow(new String [] {ad,soyad,esya} );
            this.kullanicilar.add(new Musteri(ad,soyad,esya));
            txtHata.setText("Başarıyla Eklendi.");
        } else {
            txtHata.setText("Eksik bilgiyle eklenemez !");
        }  
    }//GEN-LAST:event_btnEkleActionPerformed

    private void btnKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaydetActionPerformed
        try{
            File temizleme = new File("VeriTabani.txt");
            FileWriter fileWriter = new FileWriter(temizleme);
            fileWriter.write("\0");
            fileWriter.close();
            
            
            File dosya = new File("VeriTabani.txt");//proje içinde VeriTabani.txt adındaki txt içine yazar.
            FileWriter yazma = new FileWriter(dosya);             
            int i;
            for( i = 0 ; i < this.kullanicilar.size() ; i++ ){
                yazma.write(this.kullanicilar.get(i).getIsim() + "\n");
                yazma.write(this.kullanicilar.get(i).getSoyisim() + "\n");
                yazma.write(this.kullanicilar.get(i).getEsyasi() + "\n");
            }
            txtHata.setText("Dosyaya Kaydedildi.");
            yazma.close();
        } catch (IOException e) {
            txtHata.setText("Dosyaya yazamadı!!");
        }
    }//GEN-LAST:event_btnKaydetActionPerformed

    private void txtAdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAdFocusGained
txtHata.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdFocusGained

    private void txtSoyadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSoyadFocusGained
txtHata.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoyadFocusGained

    private void txtEsyaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEsyaFocusGained
txtHata.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_txtEsyaFocusGained

    private void btnAdmin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmin2ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdmin2ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin2;
    private javax.swing.JButton btnCikar;
    private javax.swing.JButton btnEkle;
    private javax.swing.JButton btnKaydet;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAd;
    private javax.swing.JLabel lblBaslik;
    private javax.swing.JLabel lblEsya;
    private javax.swing.JLabel lblSoyad;
    private javax.swing.JTextField txtAd;
    private javax.swing.JTextField txtEsya;
    private javax.swing.JTextField txtHata;
    private javax.swing.JTextField txtSoyad;
    // End of variables declaration//GEN-END:variables
}
